name: macOS integration
on:
  push:
    branches: [ main ]
  schedule:
    # check compatibility e.g. with brew or vscode database every Monday
    - cron:  '0 8 * * 1'
jobs:
  integration-test:
    name: Full scenario
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install pre-requirements
        run: |
          brew update
          brew upgrade
          brew install vim git fish
          brew remove go@1.15
          git config --global user.name testname
          git config --global user.email testmail
      - name: Bootstrap
        run: |
          fish scripts/bootstrap.fish
      
