name: macOS integration
on:
  push:
    branches: [ main ]
  schedule:
    # check compatibility e.g. with brew or vscode database every Monday
    - cron:  '0 8 * * 1'
jobs:
  integration-test:
    name: Full scenario
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prerequisites
        run: |
          echo "brew configuration"
          echo $(brew list)
          brew update
          brew install vim git fish
          brew install tmux
          brew remove go
          rm /usr/local/bin/go
          rm /usr/local/bin/gofmt
          brew install --cask visual-studio-code
          git config --global user.name testname
          git config --global user.email testmail
      - name: Bootstrap
        run: |
          fish scripts/bootstrap.fish
      
