name: macOS integration
on:
  push:
    branches: [ main ]
  schedule:
    # check compatibility e.g. with brew or vscode database every Monday
    - cron:  '0 8 * * 1'
jobs:
  integration-test:
    name: Check dependencies
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prerequisites
        run: |
          echo "brew configuration"
          echo $(brew list)
          brew update
          brew install fish
          brew install --cask visual-studio-code
      - name: Bootstrap
        run: |
          fish tests/deps.fish 
